language: node_js
node_js:
  - "stable"
cache:
  directory:
    - node_modules
install:
  - yarn
env:
  - CI=true
script:
  - npm run doc:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs
  on:
    branch: master
